apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
 # namespace: harsha
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['/bin/sh','-c','sleep 3000']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
